#!/usr/bin/env bash
# Configuring my Nginx server to have a custom 404 page that contains a string

sudo apt-get update
sudo apt-get install -y nginx

echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

service nginx restart
