#!/usr/bin/env bash
# Script that Installs and configures HAproxy on the lb-01 server

sudo apt-get update -y
sudo apt-get install haproxy -y

# Configure HAProxy using roundrobin algorithm
echo "
frontend http_front
        bind *:80
        default_backend http_back
backend http_back
        balance roundrobin
        server 168794-web-01 34.207.58.245:80 check
        server 168794-web-02 54.237.33.18:80 check
">> /etc/haproxy/haproxy.cfg

# Enable HAProxy management
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

sudo service haproxy restart
