#!/usr/bin/env bash
# Configures Nginx server to listen on port 80 from port 8080 and kill it
cp -r /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
sudo pkill -o nginx
