#!/usr/bin/env bash
# Script that accepts one argument and should run the whoami command under the user passed as an argument

if [ $# -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

$1=username

sudo -u "$username" whoami
